---
title: "Introduction to Design"
author: "BIOE 498/598"
date: "2/5/2020"
output: beamer_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(digits=2)
coefs <- function(model) round(model$coefficients, 2)
library(magrittr)
```

## Definitions

- \textbf{Experiment} or \textbf{Run}. A single action with the change of at least one variable followed by an observation.
- \textbf{Experimental Unit}. An instance of the item under study that is changed.
- \textbf{Observational Unit}. \emph{We'll come back to this.}
- \textbf{Independent Variable} or \textbf{Factor}. The thing under study that can be controlled or changed.
- \textbf{Background} or \textbf{Lurking Variable}. A thing we are unaware of or cannot control.
- \textbf{Dependent Variable} or \textbf{Response}. The things we measure. Depends on the settings of the independent and lurking variables.

## Definitions (continued)

- \textbf{Effect}. The change in response due to a change in independent or lurking variable.
  - \textbf{Calculated effects} come from the model.
  - \textbf{Practical effects} come from our knowledge of the system.
- \textbf{Replicate}. Two or more experiments conducted with the same settings on different experimental units.
  - The respones of replicates vary due to differences inherent in experimental units or the lurking variables.
- \textbf{Duplicates}. Multiple measurements on the same experimental unit.
  - Duplicates should always be averaged before analysis.

## Definitions (continued)

- \textbf{Experimental Design}. Collection of experiments planned in advance.
- \textbf{Confounded Factors}. When a change in factor corresponds with an identical change in another factor.
- \textbf{Biased Factors}. When a change in a factor coincides to a change in a lurking variable.
- \textbf{Experimental Error}. Difference between observed response and long run average of all experiments with the same settings.
  - There is nothing wrong with error.
  - \textbf{Bias error} remains constant or changes consistently.
  - \textbf{Random error} changes unpredictably \emph{and averages to zero}.
  
## Overall experiment design

- Use a proper experimental design.
- Randomize as much as you can.

## Designs we will study

- Completely Randomized Design
- Factorial Designs
- Fractional Factorial Designs
- Response Surface Designs
- Crossover Designs
- Screening and Sequential Designs

