---
title: "Lecture 02"
author: "Paul Jensen"
date: "11/19/2019"
output:
  ioslides_presentation:
    smaller: true
---

```{r echo=FALSE}
knitr::knit_hooks$set(mysize = function(before, options, envir) {
  if (before) 
    return(options$size)
})
```

```{r, include=FALSE}
library(tibble)
library(ggplot2)
library(cowplot)
theme_set(theme_cowplot())
```

## Null distribution of birth day-of-month
```{r, echo=FALSE}
k <- 6
n <- 100000
diffs <- numeric(n)
get_sample <- function() round(runif(k, 1, 31))
for (i in 1:n) {
  diffs[i] <- mean(get_sample()) - mean(get_sample())
}
plot(density(diffs))
```

## Testing a new blood presure medication
```{r, include=FALSE}
library(tibble)
data <- tribble(
  ~BPchange, ~treated, ~male,
  -0.5252988, TRUE, FALSE,
  4.1742790,  TRUE, FALSE,
  6.0256724, TRUE, TRUE,
  -1.4029857, TRUE, FALSE,
  0.4926655,  TRUE, FALSE,
  12.8885132,  FALSE, TRUE,
  6.7517331, FALSE, TRUE,
  4.9016320, TRUE, FALSE,
  45.95538,  FALSE, TRUE,
  19.05073,  FALSE, FALSE,
  30.32632,  TRUE, TRUE,
  33.18965,  FALSE, TRUE,
  5.73430,  TRUE, FALSE,
  33.07533,  FALSE, TRUE,
  5.58772,  FALSE, FALSE,
  31.44072,  FALSE, TRUE
)
```

```{r}
data
```

## Does our BP treatment work?
```{r}
qplot(data=data, x=treated, y=BPchange)
```

## Hypothesis testing the treatment effect
```{r}
t.test(BPchange ~ treated, data=data)
```


## A linear model with effect of treatment

```{r}
model <- lm(BPchange ~ treated, data)
summary(model)
```

## What else could explain the effect?
```{r}
summary(lm(BPchange ~ treated + male, data))
```

## Does our BP treatment work?
```{r}
qplot(data=data, x=treated, y=BPchange, color=male)
```
